name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'  # 忽略 tag 推送触发，避免发布 release 时死循环构建

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=theos_version_commit-sdks_version_commit >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-theos-sdk-version

      - name: Prepare Theos
        uses: axs66/theos-action@main

      - name: Build package
        run: |
          rm -f ${{ github.workspace }}/packages/*.deb
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated Deb packages
        run: ls ${{ github.workspace }}/packages

      - name: Create GitHub Release
        id: release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "ImmortalizerJailed $VERSION" --notes "Automated release of .deb files"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ImmortalizerJailed
          path: ${{ github.workspace }}/packages/*.deb
